spring:
  main:
    banner-mode: off
  application:
    name: Dummy Bank application
  datasource:
    url: jdbc:h2:mem:dummy-bank
    username: sa
    password:
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /api
